# https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions
name: Pull Request

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  lint_code:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11"]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install .[dev]
    - name: Analysing the code with pre-commit lint checks
      run: |
        pre-commit run -a

  test_code_python3p8:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8"]
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install .[dev]
    - name: Test code
      run: |
        mkdir test_report
        tox


  test_code_and_coverage_report_python3p11:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11"]
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install .[dev]
    - name: Test code
      run: |
        mkdir test_report
        tox
    - name: html to pdf
      uses: fifsky/html-to-pdf-action@master
      with:
        htmlFile: test_report/cov_report/index.html
        outputFile: test_report/cov_report/cov_report.pdf
        pdfOptions: '{"format": "A4", "margin": {"top": "10mm", "left": "10mm", "right": "10mm", "bottom": "10mm"}}'
    - name: Archive code coverage results
      uses: actions/upload-artifact@v4
      with:
        name: code-coverage-report
        path: test_report/cov_report/cov_report.pdf