# https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions
name: Push to branch

on:
  push:
    branches:
      - '*'

jobs:
  test_code:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.12"]
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install .[dev]
    - name: Test code
      run: |
        tox
